### ISSUE TITLE
How to use this repo with EasyOCR

### ISSUE THREAD

**Issue by yhammadmufin** [abizovnuralem/ocr#1]
Hello @abizovnuralem  I hope you are doing well. I want to use this repo for EasyOCR can you please modified the code where to change?

**Comment by abizovnuralem** [comment]
This repo is originally designed for Pytesseract, but you can modify task.py to execute EasyOCR:
replace this "text = pytesseract.image_to_string("img.jpg")" with analog of EasyOCR
